- name: Install MemCached on Ubuntu
  apt:
    name:
      - memcached
      - python3-memcache
    state: latest

- name: Modify MemCached Configuration
  lineinfile:
    dest: /etc/memcached.conf
    regexp: "-1 127.0.0.1"
    line: "-1 10.0.0.11"
    state: present
    backup: yes

- name: Restart MemCached Service
  service:
    name: memcached
    state: restarted
    enabled: true
